# starts a postgres instance
version: '3.6'
services:
  postgres:
    image: postgres:13
    ports:
      - '5466:5432' # expose pg on port 5466 to not collide with pg from elsewhere
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
