import { GradeSystemsSchema, RouteKindSchema } from "@andescalada/db/zod";

export const gradeUnitsByRouteKind = {
  [RouteKindSchema.Enum.Boulder]: [
    GradeSystemsSchema.Enum.Hueco,
    GradeSystemsSchema.Enum.Font,
  ],
  [RouteKindSchema.Enum.Sport]: [
    GradeSystemsSchema.Enum.French,
    GradeSystemsSchema.Enum.Yosemite,
  ],
  [RouteKindSchema.Enum.Trad]: [
    GradeSystemsSchema.Enum.French,
    GradeSystemsSchema.Enum.Yosemite,
  ],
  [RouteKindSchema.Enum.Mixed]: [GradeSystemsSchema.Enum.Mixed],
  [RouteKindSchema.Enum.Ice]: [GradeSystemsSchema.Enum.Ice],
  [RouteKindSchema.Enum.Aid]: [GradeSystemsSchema.Enum.Aid],
};

export const gradeUnits = {
  [GradeSystemsSchema.Enum.French]: [
    "1",
    "2",
    "2a",
    "3",
    "4a",
    "4b",
    "4c",
    "4d",
    "5a",
    "5b",
    "5c",
    "6a",
    "6a+",
    "6b",
    "6b+",
    "6c",
    "6c+",
    "7a",
    "7a+",
    "7b",
    "7b+",
    "7c",
    "7c+",
    "8a",
    "8a+",
    "8b",
    "8b+",
    "8c",
    "8c+",
    "9a",
    "9a+",
    "9b",
    "9b+",
    "9c",
    "9c+",
  ],
  [GradeSystemsSchema.Enum.Yosemite]: [
    "5",
    "5.1",
    "5.2",
    "5.3",
    "5.4",
    "5.5",
    "5.6",
    "5.7",
    "5.8",
    "5.9",
    "5.10a",
    "5.10b",
    "5.10c",
    "5.10d",
    "5.11a",
    "5.11b",
    "5.11c",
    "5.11d",
    "5.12a",
    "5.12b",
    "5.12c",
    "5.12d",
    "5.13a",
    "5.13b",
    "5.13c",
    "5.13d",
    "5.14a",
    "5.14b",
    "5.14c",
    "5.14d",
    "5.15a",
    "5.15b",
    "5.15c",
    "5.15d",
    "5.16a",
  ],
  [GradeSystemsSchema.Enum.Hueco]: [
    "V0",
    "V1",
    "V2",
    "V3",
    "V4",
    "V5",
    "V6",
    "V7",
    "V8",
    "V9",
    "V10",
    "V11",
    "V12",
    "V13",
    "V14",
    "V15",
    "V16",
    "V17",
    "V18",
  ],
  [GradeSystemsSchema.Enum.Font]: [
    "4",
    "5",
    "5+",
    "6a",
    "6a+",
    "6b",
    "6b+",
    "6c",
    "6c+",
    "7a",
    "7a+",
    "7b",
    "7b+",
    "7c",
    "7c+",
    "8a",
    "8a+",
    "8b",
    "8b+",
    "8c",
    "8c+",
    "9a",
    "9a+",
  ],
  [GradeSystemsSchema.Enum.Ice]: [
    "WI0",
    "WI1",
    "WI2",
    "WI3",
    "WI4",
    "WI5",
    "WI6",
    "WI7",
    "WI8",
  ],
  [GradeSystemsSchema.Enum.Mixed]: [
    "M1",
    "M2",
    "M3",
    "M4",
    "M5",
    "M6",
    "M7",
    "M8",
    "M9",
    "M10",
    "M11",
    "M12",
  ],
  [GradeSystemsSchema.Enum.Aid]: [
    "A0",
    "A1",
    "A2",
    "A2+",
    "A3",
    "A3+",
    "A4",
    "A4+",
    "A5",
    "A5+",
    "A6",
  ],
};

export const gradeConversion = {
  [GradeSystemsSchema.Enum.French]: {
    [GradeSystemsSchema.Enum.Yosemite]: {
      [gradeUnits[GradeSystemsSchema.Enum.French][0]]: "5.0",
      [gradeUnits[GradeSystemsSchema.Enum.French][1]]: "5.0",
      [gradeUnits[GradeSystemsSchema.Enum.French][2]]: "5.1",
      [gradeUnits[GradeSystemsSchema.Enum.French][3]]: "5.2",
      [gradeUnits[GradeSystemsSchema.Enum.French][4]]: "5.3",
      [gradeUnits[GradeSystemsSchema.Enum.French][5]]: "5.4",
      [gradeUnits[GradeSystemsSchema.Enum.French][6]]: "5.5",
      [gradeUnits[GradeSystemsSchema.Enum.French][7]]: "5.6",
      [gradeUnits[GradeSystemsSchema.Enum.French][8]]: "5.7",
      [gradeUnits[GradeSystemsSchema.Enum.French][9]]: "5.8",
      [gradeUnits[GradeSystemsSchema.Enum.French][10]]: "5.9",
      [gradeUnits[GradeSystemsSchema.Enum.French][11]]: "5.10a",
      [gradeUnits[GradeSystemsSchema.Enum.French][12]]: "5.10b",
      [gradeUnits[GradeSystemsSchema.Enum.French][13]]: "5.10c",
      [gradeUnits[GradeSystemsSchema.Enum.French][14]]: "5.10d",
      [gradeUnits[GradeSystemsSchema.Enum.French][15]]: "5.11a",
      [gradeUnits[GradeSystemsSchema.Enum.French][16]]: "5.11b/c",
      [gradeUnits[GradeSystemsSchema.Enum.French][17]]: "5.11d",
      [gradeUnits[GradeSystemsSchema.Enum.French][18]]: "5.12a",
      [gradeUnits[GradeSystemsSchema.Enum.French][19]]: "5.12b",
      [gradeUnits[GradeSystemsSchema.Enum.French][20]]: "5.12c",
      [gradeUnits[GradeSystemsSchema.Enum.French][21]]: "5.12d",
      [gradeUnits[GradeSystemsSchema.Enum.French][22]]: "5.13a",
      [gradeUnits[GradeSystemsSchema.Enum.French][23]]: "5.13b",
      [gradeUnits[GradeSystemsSchema.Enum.French][24]]: "5.13c",
      [gradeUnits[GradeSystemsSchema.Enum.French][25]]: "5.13d",
      [gradeUnits[GradeSystemsSchema.Enum.French][26]]: "5.14a",
      [gradeUnits[GradeSystemsSchema.Enum.French][27]]: "5.14b",
      [gradeUnits[GradeSystemsSchema.Enum.French][28]]: "5.14c",
      [gradeUnits[GradeSystemsSchema.Enum.French][29]]: "5.14d",
      [gradeUnits[GradeSystemsSchema.Enum.French][30]]: "5.15a",
      [gradeUnits[GradeSystemsSchema.Enum.French][31]]: "5.15b",
      [gradeUnits[GradeSystemsSchema.Enum.French][32]]: "5.15c",
      [gradeUnits[GradeSystemsSchema.Enum.French][33]]: "5.15d",
      [gradeUnits[GradeSystemsSchema.Enum.French][34]]: "5.16a",
    },
  },
  [GradeSystemsSchema.Enum.Yosemite]: {
    [GradeSystemsSchema.Enum.French]: {
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][0]]: "1",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][1]]: "2",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][2]]: "2a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][3]]: "3",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][4]]: "4a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][5]]: "4b",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][6]]: "4d",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][7]]: "5a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][8]]: "5b",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][9]]: "5c",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][10]]: "6a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][11]]: "6a+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][12]]: "6b",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][13]]: "6b+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][14]]: "6c",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][15]]: "6c/6c+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][16]]: "6c+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][17]]: "7a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][18]]: "7a+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][19]]: "7b",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][20]]: "7b+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][21]]: "7c",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][22]]: "7c+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][23]]: "8a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][24]]: "8a+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][25]]: "8b",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][26]]: "8b+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][27]]: "8c",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][28]]: "8c+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][29]]: "9a",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][30]]: "9a+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][31]]: "9b",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][32]]: "9b+",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][33]]: "9c",
      [gradeUnits[GradeSystemsSchema.Enum.Yosemite][34]]: "9c+",
    },
  },
  [GradeSystemsSchema.Enum.Hueco]: {
    [GradeSystemsSchema.Enum.Font]: {
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][0]]: "4",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][1]]: "5",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][2]]: "5+",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][3]]: "6a",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][4]]: "6b",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][5]]: "6c",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][6]]: "7a",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][7]]: "7a+",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][8]]: "7b",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][9]]: "7c",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][10]]: "7c+",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][11]]: "8a",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][12]]: "8a+",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][13]]: "8b",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][14]]: "8b+",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][15]]: "8c",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][16]]: "8c+",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][17]]: "9a",
      [gradeUnits[GradeSystemsSchema.Enum.Hueco][18]]: "9a+",
    },
  },
  [GradeSystemsSchema.Enum.Font]: {
    [GradeSystemsSchema.Enum.Hueco]: {
      [gradeUnits[GradeSystemsSchema.Enum.Font][0]]: "V0",
      [gradeUnits[GradeSystemsSchema.Enum.Font][1]]: "V1",
      [gradeUnits[GradeSystemsSchema.Enum.Font][2]]: "V2",
      [gradeUnits[GradeSystemsSchema.Enum.Font][3]]: "V3",
      [gradeUnits[GradeSystemsSchema.Enum.Font][4]]: "V3/4",
      [gradeUnits[GradeSystemsSchema.Enum.Font][5]]: "V4",
      [gradeUnits[GradeSystemsSchema.Enum.Font][6]]: "V4/5",
      [gradeUnits[GradeSystemsSchema.Enum.Font][7]]: "V5",
      [gradeUnits[GradeSystemsSchema.Enum.Font][8]]: "V5/6",
      [gradeUnits[GradeSystemsSchema.Enum.Font][9]]: "V6",
      [gradeUnits[GradeSystemsSchema.Enum.Font][10]]: "V7",
      [gradeUnits[GradeSystemsSchema.Enum.Font][11]]: "V8",
      [gradeUnits[GradeSystemsSchema.Enum.Font][12]]: "V8/9",
      [gradeUnits[GradeSystemsSchema.Enum.Font][13]]: "V9",
      [gradeUnits[GradeSystemsSchema.Enum.Font][14]]: "V10",
      [gradeUnits[GradeSystemsSchema.Enum.Font][15]]: "V11",
      [gradeUnits[GradeSystemsSchema.Enum.Font][16]]: "V12",
      [gradeUnits[GradeSystemsSchema.Enum.Font][17]]: "V13",
      [gradeUnits[GradeSystemsSchema.Enum.Font][18]]: "V14",
      [gradeUnits[GradeSystemsSchema.Enum.Font][19]]: "V15",
      [gradeUnits[GradeSystemsSchema.Enum.Font][20]]: "V16",
      [gradeUnits[GradeSystemsSchema.Enum.Font][21]]: "V17",
      [gradeUnits[GradeSystemsSchema.Enum.Font][22]]: "V18",
    },
  },
};
