const base = "./components/";

export const Icons = {
  "camping-color": require(base + "camping-color").default,
  "camping": require(base + "camping").default,
  "dog-color": require(base + "dog-color").default,
  "dog": require(base + "dog").default,
  "fire-color": require(base + "fire-color").default,
  "fire": require(base + "fire").default,
  "no-camping-color": require(base + "no-camping-color").default,
  "no-camping": require(base + "no-camping").default,
  "no-dog-color": require(base + "no-dog-color").default,
  "no-dog": require(base + "no-dog").default,
  "no-fire-color": require(base + "no-fire-color").default,
  "no-fire": require(base + "no-fire").default,
  "paid-hands-color": require(base + "paid-hands-color").default,
  "paid-hands": require(base + "paid-hands").default,
  "poop-bag-color": require(base + "poop-bag-color").default,
  "poop-bag": require(base + "poop-bag").default,
  "question-mark-color": require(base + "question-mark-color").default,
  "question-mark": require(base + "question-mark").default,
  "shake-hands-color": require(base + "shake-hands-color").default,
  "shake-hands": require(base + "shake-hands").default,
  "toilet-color": require(base + "toilet-color").default,
  "toilet": require(base + "toilet").default,
};
